// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: myncer/song.proto

package myncer_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Song struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The deterministic, reproducible ID of a bunch of details about the song.
	// In practical terms this is a hash of the song details. See `GetSongId` for impl details.`
	Id         string     `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Name       string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArtistName []string   `protobuf:"bytes,2,rep,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	AlbumName  string     `protobuf:"bytes,3,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	Datasource Datasource `protobuf:"varint,4,opt,name=datasource,proto3,enum=myncer.Datasource" json:"datasource,omitempty"`
	// Unique, stable song identifier for the datasource.
	DatasourceSongId string `protobuf:"bytes,5,opt,name=datasource_song_id,json=datasourceSongId,proto3" json:"datasource_song_id,omitempty"`
	Isrc             string `protobuf:"bytes,7,opt,name=isrc,proto3" json:"isrc,omitempty"` // next: 8
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Song) Reset() {
	*x = Song{}
	mi := &file_myncer_song_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Song) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Song) ProtoMessage() {}

func (x *Song) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_song_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Song.ProtoReflect.Descriptor instead.
func (*Song) Descriptor() ([]byte, []int) {
	return file_myncer_song_proto_rawDescGZIP(), []int{0}
}

func (x *Song) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Song) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Song) GetArtistName() []string {
	if x != nil {
		return x.ArtistName
	}
	return nil
}

func (x *Song) GetAlbumName() string {
	if x != nil {
		return x.AlbumName
	}
	return ""
}

func (x *Song) GetDatasource() Datasource {
	if x != nil {
		return x.Datasource
	}
	return Datasource_DATASOURCE_UNSPECIFIED
}

func (x *Song) GetDatasourceSongId() string {
	if x != nil {
		return x.DatasourceSongId
	}
	return ""
}

func (x *Song) GetIsrc() string {
	if x != nil {
		return x.Isrc
	}
	return ""
}

var File_myncer_song_proto protoreflect.FileDescriptor

const file_myncer_song_proto_rawDesc = "" +
	"\n" +
	"\x11myncer/song.proto\x12\x06myncer\x1a\x17myncer/datasource.proto\"\xe0\x01\n" +
	"\x04Song\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vartist_name\x18\x02 \x03(\tR\n" +
	"artistName\x12\x1d\n" +
	"\n" +
	"album_name\x18\x03 \x01(\tR\talbumName\x122\n" +
	"\n" +
	"datasource\x18\x04 \x01(\x0e2\x12.myncer.DatasourceR\n" +
	"datasource\x12,\n" +
	"\x12datasource_song_id\x18\x05 \x01(\tR\x10datasourceSongId\x12\x12\n" +
	"\x04isrc\x18\a \x01(\tR\x04isrcB3Z1github.com/hansbala/myncer/proto/myncer;myncer_pbb\x06proto3"

var (
	file_myncer_song_proto_rawDescOnce sync.Once
	file_myncer_song_proto_rawDescData []byte
)

func file_myncer_song_proto_rawDescGZIP() []byte {
	file_myncer_song_proto_rawDescOnce.Do(func() {
		file_myncer_song_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myncer_song_proto_rawDesc), len(file_myncer_song_proto_rawDesc)))
	})
	return file_myncer_song_proto_rawDescData
}

var file_myncer_song_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_myncer_song_proto_goTypes = []any{
	(*Song)(nil),    // 0: myncer.Song
	(Datasource)(0), // 1: myncer.Datasource
}
var file_myncer_song_proto_depIdxs = []int32{
	1, // 0: myncer.Song.datasource:type_name -> myncer.Datasource
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_myncer_song_proto_init() }
func file_myncer_song_proto_init() {
	if File_myncer_song_proto != nil {
		return
	}
	file_myncer_datasource_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myncer_song_proto_rawDesc), len(file_myncer_song_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_myncer_song_proto_goTypes,
		DependencyIndexes: file_myncer_song_proto_depIdxs,
		MessageInfos:      file_myncer_song_proto_msgTypes,
	}.Build()
	File_myncer_song_proto = out.File
	file_myncer_song_proto_goTypes = nil
	file_myncer_song_proto_depIdxs = nil
}
