// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: myncer/sync.proto

package myncer_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncStatus int32

const (
	SyncStatus_SYNC_STATUS_UNSPECIFIED SyncStatus = 0
	// The sync is pending and has not started yet.
	SyncStatus_SYNC_STATUS_PENDING SyncStatus = 1
	// The sync is currently running.
	SyncStatus_SYNC_STATUS_RUNNING SyncStatus = 2
	// The sync has completed successfully.
	SyncStatus_SYNC_STATUS_COMPLETED SyncStatus = 3
	// The sync has failed.
	SyncStatus_SYNC_STATUS_FAILED SyncStatus = 4
	// The sync was cancelled.
	SyncStatus_SYNC_STATUS_CANCELLED SyncStatus = 5
)

// Enum value maps for SyncStatus.
var (
	SyncStatus_name = map[int32]string{
		0: "SYNC_STATUS_UNSPECIFIED",
		1: "SYNC_STATUS_PENDING",
		2: "SYNC_STATUS_RUNNING",
		3: "SYNC_STATUS_COMPLETED",
		4: "SYNC_STATUS_FAILED",
		5: "SYNC_STATUS_CANCELLED",
	}
	SyncStatus_value = map[string]int32{
		"SYNC_STATUS_UNSPECIFIED": 0,
		"SYNC_STATUS_PENDING":     1,
		"SYNC_STATUS_RUNNING":     2,
		"SYNC_STATUS_COMPLETED":   3,
		"SYNC_STATUS_FAILED":      4,
		"SYNC_STATUS_CANCELLED":   5,
	}
)

func (x SyncStatus) Enum() *SyncStatus {
	p := new(SyncStatus)
	*p = x
	return p
}

func (x SyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_myncer_sync_proto_enumTypes[0].Descriptor()
}

func (SyncStatus) Type() protoreflect.EnumType {
	return &file_myncer_sync_proto_enumTypes[0]
}

func (x SyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncStatus.Descriptor instead.
func (SyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{0}
}

// Representative of multiple sources -> one destination.
type PlaylistMergeSync struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sources           []*MusicSource         `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	Destination       *MusicSource           `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	OverwriteExisting bool                   `protobuf:"varint,3,opt,name=overwrite_existing,json=overwriteExisting,proto3" json:"overwrite_existing,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlaylistMergeSync) Reset() {
	*x = PlaylistMergeSync{}
	mi := &file_myncer_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistMergeSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistMergeSync) ProtoMessage() {}

func (x *PlaylistMergeSync) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistMergeSync.ProtoReflect.Descriptor instead.
func (*PlaylistMergeSync) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{0}
}

func (x *PlaylistMergeSync) GetSources() []*MusicSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *PlaylistMergeSync) GetDestination() *MusicSource {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *PlaylistMergeSync) GetOverwriteExisting() bool {
	if x != nil {
		return x.OverwriteExisting
	}
	return false
}

type Sync struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// google/uuid generated UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Myncer user id.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Metadata which is fetched from SQL (for it's ACID compliance).
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Holds the actual sync data.
	//
	// Types that are valid to be assigned to SyncVariant:
	//
	//	*Sync_OneWaySync
	//	*Sync_PlaylistMergeSync
	SyncVariant   isSync_SyncVariant `protobuf_oneof:"sync_variant"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync) Reset() {
	*x = Sync{}
	mi := &file_myncer_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync) ProtoMessage() {}

func (x *Sync) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync.ProtoReflect.Descriptor instead.
func (*Sync) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{1}
}

func (x *Sync) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sync) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Sync) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Sync) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Sync) GetSyncVariant() isSync_SyncVariant {
	if x != nil {
		return x.SyncVariant
	}
	return nil
}

func (x *Sync) GetOneWaySync() *OneWaySync {
	if x != nil {
		if x, ok := x.SyncVariant.(*Sync_OneWaySync); ok {
			return x.OneWaySync
		}
	}
	return nil
}

func (x *Sync) GetPlaylistMergeSync() *PlaylistMergeSync {
	if x != nil {
		if x, ok := x.SyncVariant.(*Sync_PlaylistMergeSync); ok {
			return x.PlaylistMergeSync
		}
	}
	return nil
}

type isSync_SyncVariant interface {
	isSync_SyncVariant()
}

type Sync_OneWaySync struct {
	OneWaySync *OneWaySync `protobuf:"bytes,5,opt,name=one_way_sync,json=oneWaySync,proto3,oneof"`
}

type Sync_PlaylistMergeSync struct {
	PlaylistMergeSync *PlaylistMergeSync `protobuf:"bytes,6,opt,name=playlist_merge_sync,json=playlistMergeSync,proto3,oneof"`
}

func (*Sync_OneWaySync) isSync_SyncVariant() {}

func (*Sync_PlaylistMergeSync) isSync_SyncVariant() {}

type SyncRun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the sync that was run.
	SyncId string `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	// The run id of this sync.
	// This is expected to be randomly generated for each sync run.
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// The status of this sync run.
	SyncStatus SyncStatus `protobuf:"varint,3,opt,name=sync_status,json=syncStatus,proto3,enum=myncer.SyncStatus" json:"sync_status,omitempty"`
	// Metadata which is fetched from SQL (for it's ACID compliance).
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Lista de canciones no encontradas durante la sincronización
	UnmatchedSongs []*Song `protobuf:"bytes,6,rep,name=unmatched_songs,json=unmatchedSongs,proto3" json:"unmatched_songs,omitempty"`
	// Mensaje de error detallado (ej. playlist eliminada)
	ErrorMessage  string `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRun) Reset() {
	*x = SyncRun{}
	mi := &file_myncer_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRun) ProtoMessage() {}

func (x *SyncRun) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRun.ProtoReflect.Descriptor instead.
func (*SyncRun) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRun) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

func (x *SyncRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SyncRun) GetSyncStatus() SyncStatus {
	if x != nil {
		return x.SyncStatus
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *SyncRun) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SyncRun) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SyncRun) GetUnmatchedSongs() []*Song {
	if x != nil {
		return x.UnmatchedSongs
	}
	return nil
}

func (x *SyncRun) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Representative of source -> destination.
type OneWaySync struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Source      *MusicSource           `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination *MusicSource           `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	// When true, it overwrites the destination songs.
	// If a song exists in source but not in destination, the song will be lost from destination.
	OverwriteExisting bool `protobuf:"varint,3,opt,name=overwrite_existing,json=overwriteExisting,proto3" json:"overwrite_existing,omitempty"` // next: 4
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OneWaySync) Reset() {
	*x = OneWaySync{}
	mi := &file_myncer_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneWaySync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneWaySync) ProtoMessage() {}

func (x *OneWaySync) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneWaySync.ProtoReflect.Descriptor instead.
func (*OneWaySync) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{3}
}

func (x *OneWaySync) GetSource() *MusicSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *OneWaySync) GetDestination() *MusicSource {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *OneWaySync) GetOverwriteExisting() bool {
	if x != nil {
		return x.OverwriteExisting
	}
	return false
}

type CreateSyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sync to create.
	//
	// Types that are valid to be assigned to SyncVariant:
	//
	//	*CreateSyncRequest_OneWaySync
	//	*CreateSyncRequest_PlaylistMergeSync
	SyncVariant   isCreateSyncRequest_SyncVariant `protobuf_oneof:"sync_variant"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSyncRequest) Reset() {
	*x = CreateSyncRequest{}
	mi := &file_myncer_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSyncRequest) ProtoMessage() {}

func (x *CreateSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSyncRequest.ProtoReflect.Descriptor instead.
func (*CreateSyncRequest) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSyncRequest) GetSyncVariant() isCreateSyncRequest_SyncVariant {
	if x != nil {
		return x.SyncVariant
	}
	return nil
}

func (x *CreateSyncRequest) GetOneWaySync() *OneWaySync {
	if x != nil {
		if x, ok := x.SyncVariant.(*CreateSyncRequest_OneWaySync); ok {
			return x.OneWaySync
		}
	}
	return nil
}

func (x *CreateSyncRequest) GetPlaylistMergeSync() *PlaylistMergeSync {
	if x != nil {
		if x, ok := x.SyncVariant.(*CreateSyncRequest_PlaylistMergeSync); ok {
			return x.PlaylistMergeSync
		}
	}
	return nil
}

type isCreateSyncRequest_SyncVariant interface {
	isCreateSyncRequest_SyncVariant()
}

type CreateSyncRequest_OneWaySync struct {
	OneWaySync *OneWaySync `protobuf:"bytes,1,opt,name=one_way_sync,json=oneWaySync,proto3,oneof"`
}

type CreateSyncRequest_PlaylistMergeSync struct {
	PlaylistMergeSync *PlaylistMergeSync `protobuf:"bytes,2,opt,name=playlist_merge_sync,json=playlistMergeSync,proto3,oneof"`
}

func (*CreateSyncRequest_OneWaySync) isCreateSyncRequest_SyncVariant() {}

func (*CreateSyncRequest_PlaylistMergeSync) isCreateSyncRequest_SyncVariant() {}

type CreateSyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created sync.
	Sync          *Sync `protobuf:"bytes,1,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSyncResponse) Reset() {
	*x = CreateSyncResponse{}
	mi := &file_myncer_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSyncResponse) ProtoMessage() {}

func (x *CreateSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSyncResponse.ProtoReflect.Descriptor instead.
func (*CreateSyncResponse) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSyncResponse) GetSync() *Sync {
	if x != nil {
		return x.Sync
	}
	return nil
}

type DeleteSyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the sync to delete.
	SyncId        string `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSyncRequest) Reset() {
	*x = DeleteSyncRequest{}
	mi := &file_myncer_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSyncRequest) ProtoMessage() {}

func (x *DeleteSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSyncRequest.ProtoReflect.Descriptor instead.
func (*DeleteSyncRequest) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSyncRequest) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

type DeleteSyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the deleted sync.
	SyncId        string `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSyncResponse) Reset() {
	*x = DeleteSyncResponse{}
	mi := &file_myncer_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSyncResponse) ProtoMessage() {}

func (x *DeleteSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSyncResponse.ProtoReflect.Descriptor instead.
func (*DeleteSyncResponse) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSyncResponse) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

type ListSyncsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncsRequest) Reset() {
	*x = ListSyncsRequest{}
	mi := &file_myncer_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncsRequest) ProtoMessage() {}

func (x *ListSyncsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncsRequest.ProtoReflect.Descriptor instead.
func (*ListSyncsRequest) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{8}
}

type ListSyncsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of syncs for the current user.
	Syncs         []*Sync `protobuf:"bytes,1,rep,name=syncs,proto3" json:"syncs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncsResponse) Reset() {
	*x = ListSyncsResponse{}
	mi := &file_myncer_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncsResponse) ProtoMessage() {}

func (x *ListSyncsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncsResponse.ProtoReflect.Descriptor instead.
func (*ListSyncsResponse) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{9}
}

func (x *ListSyncsResponse) GetSyncs() []*Sync {
	if x != nil {
		return x.Syncs
	}
	return nil
}

type GetSyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the sync to get.
	SyncId        string `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncRequest) Reset() {
	*x = GetSyncRequest{}
	mi := &file_myncer_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncRequest) ProtoMessage() {}

func (x *GetSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncRequest.ProtoReflect.Descriptor instead.
func (*GetSyncRequest) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{10}
}

func (x *GetSyncRequest) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

type GetSyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested sync.
	Sync          *Sync `protobuf:"bytes,1,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncResponse) Reset() {
	*x = GetSyncResponse{}
	mi := &file_myncer_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncResponse) ProtoMessage() {}

func (x *GetSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncResponse.ProtoReflect.Descriptor instead.
func (*GetSyncResponse) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{11}
}

func (x *GetSyncResponse) GetSync() *Sync {
	if x != nil {
		return x.Sync
	}
	return nil
}

type RunSyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the sync to run.
	SyncId        string `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSyncRequest) Reset() {
	*x = RunSyncRequest{}
	mi := &file_myncer_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSyncRequest) ProtoMessage() {}

func (x *RunSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSyncRequest.ProtoReflect.Descriptor instead.
func (*RunSyncRequest) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{12}
}

func (x *RunSyncRequest) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

type RunSyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the sync that was run.
	SyncId string     `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	Status SyncStatus `protobuf:"varint,2,opt,name=status,proto3,enum=myncer.SyncStatus" json:"status,omitempty"`
	// If the sync failed, this will contain the error message.
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSyncResponse) Reset() {
	*x = RunSyncResponse{}
	mi := &file_myncer_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSyncResponse) ProtoMessage() {}

func (x *RunSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSyncResponse.ProtoReflect.Descriptor instead.
func (*RunSyncResponse) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{13}
}

func (x *RunSyncResponse) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

func (x *RunSyncResponse) GetStatus() SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *RunSyncResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListSyncRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncRunsRequest) Reset() {
	*x = ListSyncRunsRequest{}
	mi := &file_myncer_sync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncRunsRequest) ProtoMessage() {}

func (x *ListSyncRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncRunsRequest.ProtoReflect.Descriptor instead.
func (*ListSyncRunsRequest) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{14}
}

type ListSyncRunsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of sync runs for the current user.
	SyncRuns      []*SyncRun `protobuf:"bytes,1,rep,name=sync_runs,json=syncRuns,proto3" json:"sync_runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncRunsResponse) Reset() {
	*x = ListSyncRunsResponse{}
	mi := &file_myncer_sync_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncRunsResponse) ProtoMessage() {}

func (x *ListSyncRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_sync_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncRunsResponse.ProtoReflect.Descriptor instead.
func (*ListSyncRunsResponse) Descriptor() ([]byte, []int) {
	return file_myncer_sync_proto_rawDescGZIP(), []int{15}
}

func (x *ListSyncRunsResponse) GetSyncRuns() []*SyncRun {
	if x != nil {
		return x.SyncRuns
	}
	return nil
}

var File_myncer_sync_proto protoreflect.FileDescriptor

const file_myncer_sync_proto_rawDesc = "" +
	"\n" +
	"\x11myncer/sync.proto\x12\x06myncer\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17myncer/datasource.proto\x1a\x11myncer/song.proto\"\xa8\x01\n" +
	"\x11PlaylistMergeSync\x12-\n" +
	"\asources\x18\x01 \x03(\v2\x13.myncer.MusicSourceR\asources\x125\n" +
	"\vdestination\x18\x02 \x01(\v2\x13.myncer.MusicSourceR\vdestination\x12-\n" +
	"\x12overwrite_existing\x18\x03 \x01(\bR\x11overwriteExisting\"\xba\x02\n" +
	"\x04Sync\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\fone_way_sync\x18\x05 \x01(\v2\x12.myncer.OneWaySyncH\x00R\n" +
	"oneWaySync\x12K\n" +
	"\x13playlist_merge_sync\x18\x06 \x01(\v2\x19.myncer.PlaylistMergeSyncH\x00R\x11playlistMergeSyncB\x0e\n" +
	"\fsync_variant\"\xc0\x02\n" +
	"\aSyncRun\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x123\n" +
	"\vsync_status\x18\x03 \x01(\x0e2\x12.myncer.SyncStatusR\n" +
	"syncStatus\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x125\n" +
	"\x0funmatched_songs\x18\x06 \x03(\v2\f.myncer.SongR\x0eunmatchedSongs\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"\x9f\x01\n" +
	"\n" +
	"OneWaySync\x12+\n" +
	"\x06source\x18\x01 \x01(\v2\x13.myncer.MusicSourceR\x06source\x125\n" +
	"\vdestination\x18\x02 \x01(\v2\x13.myncer.MusicSourceR\vdestination\x12-\n" +
	"\x12overwrite_existing\x18\x03 \x01(\bR\x11overwriteExisting\"\xa8\x01\n" +
	"\x11CreateSyncRequest\x126\n" +
	"\fone_way_sync\x18\x01 \x01(\v2\x12.myncer.OneWaySyncH\x00R\n" +
	"oneWaySync\x12K\n" +
	"\x13playlist_merge_sync\x18\x02 \x01(\v2\x19.myncer.PlaylistMergeSyncH\x00R\x11playlistMergeSyncB\x0e\n" +
	"\fsync_variant\"6\n" +
	"\x12CreateSyncResponse\x12 \n" +
	"\x04sync\x18\x01 \x01(\v2\f.myncer.SyncR\x04sync\",\n" +
	"\x11DeleteSyncRequest\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\"-\n" +
	"\x12DeleteSyncResponse\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\"\x12\n" +
	"\x10ListSyncsRequest\"7\n" +
	"\x11ListSyncsResponse\x12\"\n" +
	"\x05syncs\x18\x01 \x03(\v2\f.myncer.SyncR\x05syncs\")\n" +
	"\x0eGetSyncRequest\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\"3\n" +
	"\x0fGetSyncResponse\x12 \n" +
	"\x04sync\x18\x01 \x01(\v2\f.myncer.SyncR\x04sync\")\n" +
	"\x0eRunSyncRequest\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\"{\n" +
	"\x0fRunSyncResponse\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.myncer.SyncStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x15\n" +
	"\x13ListSyncRunsRequest\"D\n" +
	"\x14ListSyncRunsResponse\x12,\n" +
	"\tsync_runs\x18\x01 \x03(\v2\x0f.myncer.SyncRunR\bsyncRuns*\xa9\x01\n" +
	"\n" +
	"SyncStatus\x12\x1b\n" +
	"\x17SYNC_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SYNC_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13SYNC_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15SYNC_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12SYNC_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15SYNC_STATUS_CANCELLED\x10\x052\x9c\x03\n" +
	"\vSyncService\x12C\n" +
	"\n" +
	"CreateSync\x12\x19.myncer.CreateSyncRequest\x1a\x1a.myncer.CreateSyncResponse\x12C\n" +
	"\n" +
	"DeleteSync\x12\x19.myncer.DeleteSyncRequest\x1a\x1a.myncer.DeleteSyncResponse\x12@\n" +
	"\tListSyncs\x12\x18.myncer.ListSyncsRequest\x1a\x19.myncer.ListSyncsResponse\x12:\n" +
	"\aGetSync\x12\x16.myncer.GetSyncRequest\x1a\x17.myncer.GetSyncResponse\x12:\n" +
	"\aRunSync\x12\x16.myncer.RunSyncRequest\x1a\x17.myncer.RunSyncResponse\x12I\n" +
	"\fListSyncRuns\x12\x1b.myncer.ListSyncRunsRequest\x1a\x1c.myncer.ListSyncRunsResponseB3Z1github.com/hansbala/myncer/proto/myncer;myncer_pbb\x06proto3"

var (
	file_myncer_sync_proto_rawDescOnce sync.Once
	file_myncer_sync_proto_rawDescData []byte
)

func file_myncer_sync_proto_rawDescGZIP() []byte {
	file_myncer_sync_proto_rawDescOnce.Do(func() {
		file_myncer_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myncer_sync_proto_rawDesc), len(file_myncer_sync_proto_rawDesc)))
	})
	return file_myncer_sync_proto_rawDescData
}

var file_myncer_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_myncer_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_myncer_sync_proto_goTypes = []any{
	(SyncStatus)(0),               // 0: myncer.SyncStatus
	(*PlaylistMergeSync)(nil),     // 1: myncer.PlaylistMergeSync
	(*Sync)(nil),                  // 2: myncer.Sync
	(*SyncRun)(nil),               // 3: myncer.SyncRun
	(*OneWaySync)(nil),            // 4: myncer.OneWaySync
	(*CreateSyncRequest)(nil),     // 5: myncer.CreateSyncRequest
	(*CreateSyncResponse)(nil),    // 6: myncer.CreateSyncResponse
	(*DeleteSyncRequest)(nil),     // 7: myncer.DeleteSyncRequest
	(*DeleteSyncResponse)(nil),    // 8: myncer.DeleteSyncResponse
	(*ListSyncsRequest)(nil),      // 9: myncer.ListSyncsRequest
	(*ListSyncsResponse)(nil),     // 10: myncer.ListSyncsResponse
	(*GetSyncRequest)(nil),        // 11: myncer.GetSyncRequest
	(*GetSyncResponse)(nil),       // 12: myncer.GetSyncResponse
	(*RunSyncRequest)(nil),        // 13: myncer.RunSyncRequest
	(*RunSyncResponse)(nil),       // 14: myncer.RunSyncResponse
	(*ListSyncRunsRequest)(nil),   // 15: myncer.ListSyncRunsRequest
	(*ListSyncRunsResponse)(nil),  // 16: myncer.ListSyncRunsResponse
	(*MusicSource)(nil),           // 17: myncer.MusicSource
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
	(*Song)(nil),                  // 19: myncer.Song
}
var file_myncer_sync_proto_depIdxs = []int32{
	17, // 0: myncer.PlaylistMergeSync.sources:type_name -> myncer.MusicSource
	17, // 1: myncer.PlaylistMergeSync.destination:type_name -> myncer.MusicSource
	18, // 2: myncer.Sync.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: myncer.Sync.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 4: myncer.Sync.one_way_sync:type_name -> myncer.OneWaySync
	1,  // 5: myncer.Sync.playlist_merge_sync:type_name -> myncer.PlaylistMergeSync
	0,  // 6: myncer.SyncRun.sync_status:type_name -> myncer.SyncStatus
	18, // 7: myncer.SyncRun.created_at:type_name -> google.protobuf.Timestamp
	18, // 8: myncer.SyncRun.updated_at:type_name -> google.protobuf.Timestamp
	19, // 9: myncer.SyncRun.unmatched_songs:type_name -> myncer.Song
	17, // 10: myncer.OneWaySync.source:type_name -> myncer.MusicSource
	17, // 11: myncer.OneWaySync.destination:type_name -> myncer.MusicSource
	4,  // 12: myncer.CreateSyncRequest.one_way_sync:type_name -> myncer.OneWaySync
	1,  // 13: myncer.CreateSyncRequest.playlist_merge_sync:type_name -> myncer.PlaylistMergeSync
	2,  // 14: myncer.CreateSyncResponse.sync:type_name -> myncer.Sync
	2,  // 15: myncer.ListSyncsResponse.syncs:type_name -> myncer.Sync
	2,  // 16: myncer.GetSyncResponse.sync:type_name -> myncer.Sync
	0,  // 17: myncer.RunSyncResponse.status:type_name -> myncer.SyncStatus
	3,  // 18: myncer.ListSyncRunsResponse.sync_runs:type_name -> myncer.SyncRun
	5,  // 19: myncer.SyncService.CreateSync:input_type -> myncer.CreateSyncRequest
	7,  // 20: myncer.SyncService.DeleteSync:input_type -> myncer.DeleteSyncRequest
	9,  // 21: myncer.SyncService.ListSyncs:input_type -> myncer.ListSyncsRequest
	11, // 22: myncer.SyncService.GetSync:input_type -> myncer.GetSyncRequest
	13, // 23: myncer.SyncService.RunSync:input_type -> myncer.RunSyncRequest
	15, // 24: myncer.SyncService.ListSyncRuns:input_type -> myncer.ListSyncRunsRequest
	6,  // 25: myncer.SyncService.CreateSync:output_type -> myncer.CreateSyncResponse
	8,  // 26: myncer.SyncService.DeleteSync:output_type -> myncer.DeleteSyncResponse
	10, // 27: myncer.SyncService.ListSyncs:output_type -> myncer.ListSyncsResponse
	12, // 28: myncer.SyncService.GetSync:output_type -> myncer.GetSyncResponse
	14, // 29: myncer.SyncService.RunSync:output_type -> myncer.RunSyncResponse
	16, // 30: myncer.SyncService.ListSyncRuns:output_type -> myncer.ListSyncRunsResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_myncer_sync_proto_init() }
func file_myncer_sync_proto_init() {
	if File_myncer_sync_proto != nil {
		return
	}
	file_myncer_datasource_proto_init()
	file_myncer_song_proto_init()
	file_myncer_sync_proto_msgTypes[1].OneofWrappers = []any{
		(*Sync_OneWaySync)(nil),
		(*Sync_PlaylistMergeSync)(nil),
	}
	file_myncer_sync_proto_msgTypes[4].OneofWrappers = []any{
		(*CreateSyncRequest_OneWaySync)(nil),
		(*CreateSyncRequest_PlaylistMergeSync)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myncer_sync_proto_rawDesc), len(file_myncer_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myncer_sync_proto_goTypes,
		DependencyIndexes: file_myncer_sync_proto_depIdxs,
		EnumInfos:         file_myncer_sync_proto_enumTypes,
		MessageInfos:      file_myncer_sync_proto_msgTypes,
	}.Build()
	File_myncer_sync_proto = out.File
	file_myncer_sync_proto_goTypes = nil
	file_myncer_sync_proto_depIdxs = nil
}
