// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: myncer/user.proto

package myncer_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// google/uuid generated UUID.
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// golang.org/x/crypto/bcrypt generated hash of plaintext.
	HashedPassword string `protobuf:"bytes,5,opt,name=hashed_password,json=hashedPassword,proto3" json:"hashed_password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_myncer_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

// Safe to expose to the public.
type PublicUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// google/uuid generated UUID.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicUser) Reset() {
	*x = PublicUser{}
	mi := &file_myncer_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicUser) ProtoMessage() {}

func (x *PublicUser) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicUser.ProtoReflect.Descriptor instead.
func (*PublicUser) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{1}
}

func (x *PublicUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicUser) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *PublicUser) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *PublicUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FirstName string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email     string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// The plain text password of the user.
	Password      string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_myncer_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the created user.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_myncer_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoginUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// The plain text password of the user.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_myncer_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the logged in user.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_myncer_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LogoutUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the user to be logged out.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutUserRequest) Reset() {
	*x = LogoutUserRequest{}
	mi := &file_myncer_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutUserRequest) ProtoMessage() {}

func (x *LogoutUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutUserRequest.ProtoReflect.Descriptor instead.
func (*LogoutUserRequest) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LogoutUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the logged out user.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutUserResponse) Reset() {
	*x = LogoutUserResponse{}
	mi := &file_myncer_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutUserResponse) ProtoMessage() {}

func (x *LogoutUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutUserResponse.ProtoReflect.Descriptor instead.
func (*LogoutUserResponse) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EditUserRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email     string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// The plain text password of the user.
	Password      string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditUserRequest) Reset() {
	*x = EditUserRequest{}
	mi := &file_myncer_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserRequest) ProtoMessage() {}

func (x *EditUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserRequest.ProtoReflect.Descriptor instead.
func (*EditUserRequest) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{8}
}

func (x *EditUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *EditUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *EditUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EditUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EditUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *PublicUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditUserResponse) Reset() {
	*x = EditUserResponse{}
	mi := &file_myncer_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserResponse) ProtoMessage() {}

func (x *EditUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserResponse.ProtoReflect.Descriptor instead.
func (*EditUserResponse) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{9}
}

func (x *EditUserResponse) GetUser() *PublicUser {
	if x != nil {
		return x.User
	}
	return nil
}

type CurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUserRequest) Reset() {
	*x = CurrentUserRequest{}
	mi := &file_myncer_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUserRequest) ProtoMessage() {}

func (x *CurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUserRequest.ProtoReflect.Descriptor instead.
func (*CurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{10}
}

type CurrentUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *PublicUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUserResponse) Reset() {
	*x = CurrentUserResponse{}
	mi := &file_myncer_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUserResponse) ProtoMessage() {}

func (x *CurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myncer_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUserResponse.ProtoReflect.Descriptor instead.
func (*CurrentUserResponse) Descriptor() ([]byte, []int) {
	return file_myncer_user_proto_rawDescGZIP(), []int{11}
}

func (x *CurrentUserResponse) GetUser() *PublicUser {
	if x != nil {
		return x.User
	}
	return nil
}

var File_myncer_user_proto protoreflect.FileDescriptor

const file_myncer_user_proto_rawDesc = "" +
	"\n" +
	"\x11myncer/user.proto\x12\x06myncer\"\x91\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12'\n" +
	"\x0fhashed_password\x18\x05 \x01(\tR\x0ehashedPassword\"n\n" +
	"\n" +
	"PublicUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\x81\x01\n" +
	"\x11CreateUserRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"$\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"#\n" +
	"\x11LoginUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11LogoutUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12LogoutUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8f\x01\n" +
	"\x0fEditUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\":\n" +
	"\x10EditUserResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.myncer.PublicUserR\x04user\"\x14\n" +
	"\x12CurrentUserRequest\"=\n" +
	"\x13CurrentUserResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.myncer.PublicUserR\x04user2\xe3\x02\n" +
	"\vUserService\x12C\n" +
	"\n" +
	"CreateUser\x12\x19.myncer.CreateUserRequest\x1a\x1a.myncer.CreateUserResponse\x12@\n" +
	"\tLoginUser\x12\x18.myncer.LoginUserRequest\x1a\x19.myncer.LoginUserResponse\x12C\n" +
	"\n" +
	"LogoutUser\x12\x19.myncer.LogoutUserRequest\x1a\x1a.myncer.LogoutUserResponse\x12=\n" +
	"\bEditUser\x12\x17.myncer.EditUserRequest\x1a\x18.myncer.EditUserResponse\x12I\n" +
	"\x0eGetCurrentUser\x12\x1a.myncer.CurrentUserRequest\x1a\x1b.myncer.CurrentUserResponseB3Z1github.com/hansbala/myncer/proto/myncer;myncer_pbb\x06proto3"

var (
	file_myncer_user_proto_rawDescOnce sync.Once
	file_myncer_user_proto_rawDescData []byte
)

func file_myncer_user_proto_rawDescGZIP() []byte {
	file_myncer_user_proto_rawDescOnce.Do(func() {
		file_myncer_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myncer_user_proto_rawDesc), len(file_myncer_user_proto_rawDesc)))
	})
	return file_myncer_user_proto_rawDescData
}

var file_myncer_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_myncer_user_proto_goTypes = []any{
	(*User)(nil),                // 0: myncer.User
	(*PublicUser)(nil),          // 1: myncer.PublicUser
	(*CreateUserRequest)(nil),   // 2: myncer.CreateUserRequest
	(*CreateUserResponse)(nil),  // 3: myncer.CreateUserResponse
	(*LoginUserRequest)(nil),    // 4: myncer.LoginUserRequest
	(*LoginUserResponse)(nil),   // 5: myncer.LoginUserResponse
	(*LogoutUserRequest)(nil),   // 6: myncer.LogoutUserRequest
	(*LogoutUserResponse)(nil),  // 7: myncer.LogoutUserResponse
	(*EditUserRequest)(nil),     // 8: myncer.EditUserRequest
	(*EditUserResponse)(nil),    // 9: myncer.EditUserResponse
	(*CurrentUserRequest)(nil),  // 10: myncer.CurrentUserRequest
	(*CurrentUserResponse)(nil), // 11: myncer.CurrentUserResponse
}
var file_myncer_user_proto_depIdxs = []int32{
	1,  // 0: myncer.EditUserResponse.user:type_name -> myncer.PublicUser
	1,  // 1: myncer.CurrentUserResponse.user:type_name -> myncer.PublicUser
	2,  // 2: myncer.UserService.CreateUser:input_type -> myncer.CreateUserRequest
	4,  // 3: myncer.UserService.LoginUser:input_type -> myncer.LoginUserRequest
	6,  // 4: myncer.UserService.LogoutUser:input_type -> myncer.LogoutUserRequest
	8,  // 5: myncer.UserService.EditUser:input_type -> myncer.EditUserRequest
	10, // 6: myncer.UserService.GetCurrentUser:input_type -> myncer.CurrentUserRequest
	3,  // 7: myncer.UserService.CreateUser:output_type -> myncer.CreateUserResponse
	5,  // 8: myncer.UserService.LoginUser:output_type -> myncer.LoginUserResponse
	7,  // 9: myncer.UserService.LogoutUser:output_type -> myncer.LogoutUserResponse
	9,  // 10: myncer.UserService.EditUser:output_type -> myncer.EditUserResponse
	11, // 11: myncer.UserService.GetCurrentUser:output_type -> myncer.CurrentUserResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_myncer_user_proto_init() }
func file_myncer_user_proto_init() {
	if File_myncer_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myncer_user_proto_rawDesc), len(file_myncer_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myncer_user_proto_goTypes,
		DependencyIndexes: file_myncer_user_proto_depIdxs,
		MessageInfos:      file_myncer_user_proto_msgTypes,
	}.Build()
	File_myncer_user_proto = out.File
	file_myncer_user_proto_goTypes = nil
	file_myncer_user_proto_depIdxs = nil
}
